### ISSUE TITLE
Console.OpenStandardInput() does not get properly released after using it as a pipe source

### ISSUE THREAD

**Issue by paynecrl97** [Tyrrrz/CliWrap#79]
Using v 3.1.0:

After using `.WithStandardInputPipe(PipeSource.FromStream(inputStream)))`, the input stream does not appear to be correctly relinquished once the command has finished executing. 

Repro steps:

1. Run the program below
1. Once you see the `Streams disposed` message, press a character key
1. You'd expect to to see the message `Intercepted key: {key}` printed, but you don't
1. Press a few other character keys, note that the program does not progress until you press the `enter` key
1. After the `enter` key has been pressed, press a single character key. Note that the message `Intercepted key: {key}` is printed

```
using (var inputStream = Console.OpenStandardInput())
using (var errorStream = Console.OpenStandardError())
{
	var commandResult =
		await Cli.Wrap("git")
			.WithArguments("--version")
			.WithValidation(CommandResultValidation.None)
			.WithStandardInputPipe(PipeSource.FromStream(inputStream))
			.WithStandardOutputPipe(PipeTarget.ToStream(errorStream))
			.ExecuteBufferedAsync(Encoding.UTF8);
}

Console.WriteLine("Streams disposed");

var key = Console.ReadKey(intercept: true);

Console.WriteLine($"Intercepted key: {key.KeyChar}");
```

**Comment by Tyrrrz** [comment]
What behavior did you expect to happen?

**Comment by paynecrl97** [comment]
The `var key = Console.ReadKey(intercept: true);` line should have captured the first key that was pressed. Instead, It does not capture anything until I press `enter`

**Comment by Tyrrrz** [comment]
Try not disposing the input stream. My guess is that the `Console` class breaks when you do something to the stdin directly.

**Comment by DaRosenberg** [comment]
@Tyrrrz it's worth a try, but the fact that the `Console.ReadKey()´ functionality "recovers" after pressing `Enter` contradicts that somewhat IMO.

**Comment by Tyrrrz** [comment]
It does indeed seem weird. Is this on .NET Core?

**Comment by DaRosenberg** [comment]
Yeah, .NET Core 3.1.

**Comment by DaRosenberg** [comment]
It's as if the `PipeSource` is holding on to the input stream and reading bytes from it for too long, preempting `Console.ReadKey()` and leaving it with nothing. We also tried doing `autoFlush: true` on the `PipeSource` but it did not change the behavior.

**Comment by Tyrrrz** [comment]
I think `Console.ReadKey()` might not even be using stdin directly, i.e. it reads key presses sent to the window. I'm not sure though, it's been a while since I've looked at the source code of it.

`PipeSource` for `Stream` is really straightforward. It doesn't do anything after the method completes.

https://github.com/Tyrrrz/CliWrap/blob/cb483c70c7afb5dda0df37698c2dce8e411834ff/CliWrap/PipeSource.cs#L61-L74

**Comment by DaRosenberg** [comment]
> I think Console.ReadKey() might not even be using stdin directly, i.e. it reads key presses sent to the window.

Hmm... I think that's unlikely, because it would never work cross-platform, in a macOS and Linux terminal environment the streams is the only thing a process has, no access to window handles and such. And it would also make it even weirder that `Console.ReadKey()` does not receive anything just because we're mucking around with the input stream, no?

**Comment by Tyrrrz** [comment]
It's a bit too involved, but it seems there are at least some branches where it's not read on Windows:

https://github.com/dotnet/runtime/blob/e0913bd003eaa3fef6ef11c5d1380ca5005b1253/src/libraries/System.Console/src/System/ConsolePal.Windows.cs#L303-L397

Although I might be assessing it wrong.

**Comment by Tyrrrz** [comment]
I was able to reproduce the issue. I suspect what's happening is that the copy task remains alive even despite calling `inputStream.Dispose()`. Note that `git version` doesn't consume any stdin and so it exits early, thus going through the early-cancellation flow to abort copying input stream.

**Comment by DaRosenberg** [comment]
Yup, that makes sense, and it's almost exactly as I theorised above.

We initially discovered this in a more realistic scenario, not using `git --version` but rather `git mergetool`. In our real scenario, Git is happily prompting and reading characters from stdin, and eventually exits. And after that, and after having disposed the streams etc, our `Console.ReadKey()` is not working.

One thing that's still unclear to me though: what's so magic about the enter key that makes the copy task finally give up and relinquish control?

In any case, if this boils down to `WindowsConsoleStream` not respecting cancellation in a timely manner, it seems to me the only way around this would be to not use `CopyTo()` for `stdin` but instead implement some kind of custom stream-to-stream copying mechanism that *does* support cancellation properly.

**Comment by Tyrrrz** [comment]
> One thing that's still unclear to me though: what's so magic about the enter key that makes the copy task finally give up and relinquish control?

It actually didn't in my case. `Console.ReadKey()` completed but captured null character (\0) so in the end it just printed `Intercepted key: `.

> In any case, if this boils down to WindowsConsoleStream not respecting cancellation in a timely manner, it seems to me the only way around this would be to not use CopyTo() for stdin but instead implement some kind of custom stream-to-stream copying mechanism that does support cancellation properly.

Well, that's what it does. It all drills down to the `ReadAsync` method which does not respect cancellation token by default in streams and `WindowsConsoleStream` doesn't override it in any way to make it work. I had hoped that it at least did something on `Dispose()` but it looks like that method is essentially no-op as well.

Also, the reason that part of code exists is to stop reading stdin if the application has already exited, for example if you piped more than the application needs and there's no point reading past that anymore. This is especially relevant on infinite streams (one of them is `Console.OpenStandardInput()`) because otherwise the command never completes, despite the underlying application having exited already.

So it looks like fixing one bug created another one and I'm really not sure how to have them both fixed, considering that `WindowsConsoleStream` doesn't respect cancellation nor aborts any active reading operations on `Dispose()`.

**Comment by DaRosenberg** [comment]
I tested to see how this behave on macOS. The result is slightly different:

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/3889090/87937427-01f51c00-ca95-11ea-932e-75fc4d754020.png">

The ENTER key is not needed in this case, just an extra keypress.

Still not the desired behaviour though. But maybe it could give some sort of clue.

**Comment by Tyrrrz** [comment]
It boils down to:

1. `Console.OpenStandardInput` is an infinite stream, i.e. `ReadAsync` never returns `0`.
2. Its `ReadAsync` does not handle cancellation.
3. The stdin piping task has to be aborted somehow, otherwise `command.ExecuteAsync()` will be stuck forever.
4. Since we can't use a cancellation token (it ignores it), we can only stop awaiting it early and then call `Dispose()` on the stream, hoping it would cancel the task. As seen above, that doesn't work either.

**Comment by DaRosenberg** [comment]
Yes, agree 100%.

I have just finished testing another fix, which I would like to PR if you will consider it.

If we remove the redirection of STDIN for the child process completely, like this:

<img width="437" alt="image" src="https://user-images.githubusercontent.com/3889090/87942967-a9764c80-ca9d-11ea-9857-c46398de26d8.png">

Then .NET automatically pipes the input from the parent process to the child, using native mechanisms (named pipes I think) and everything works as expected.

So how about changing the default behaviour of CliWrap so that, if you don't call a `WithStandard*Pipe()` method, then the corresponding stream does not get redirected at all, but instead implicitly piped from/to the corresponding stream of the parent process. This would be a functional change of the default behaviour so I would understand if you had reservations, but on the other hand, it's closer to the default behaviour of `ProcessStartInfo` and might be what many expect in the first place.

As an alternative, we could add additional methods:

```
WithParentStandardInput()
WithParentStandandOutput()
WithParentStandardError()
```

And if you call one of those, we store it as a `bool` on the `Command` and do not do any redirection.

Would either of those be acceptable implementations for you?

**Comment by Tyrrrz** [comment]
Interesting, I wasn't aware of this behavior. I'm guessing it works because Windows applications share the same console window if they're part of the same process tree. I'm not sure if it can really be relied upon, I can't seem to find a word in documentation on `Process`/`ProcessStartInfo` that describes this behavior.

In any case, this is a very specific edge-case scenario and I'm hesitant to implement workarounds only for the sake of facilitating this one use case. Disabling redirects also has an unwanted side effect in that the data will go through the console window's buffers, which is significantly slower than redirecting it to `Stream.Null` if you plan to discard it.

**Comment by DaRosenberg** [comment]
Not sure about documentation, but this default behaviour of `Process` seems well known and also seems to work reliably across all platforms.

Regarding the performance concern, I believe my PR will address it. I'll create it soon, hang on.

**Comment by Tyrrrz** [comment]
Random tweet I've encountered that may be relevant:
https://twitter.com/daveaglick/status/1328810105555529731?s=20

![image](https://user-images.githubusercontent.com/1935960/99452082-c592d900-292b-11eb-9a82-98576b3e3da2.png)

**Comment by Tyrrrz** [comment]
Going to close this issue as it's become stale and no one has mentioned or reported anything related to it.
Looking back at the discussion, it seems that ideally the issue should be fixed on .NET's side by making `UnixConsoleStream`/`WindowsConsoleStream` respect the provided `CancellationToken`.

**Comment by DaRosenberg** [comment]
@Tyrrrz have you found an upstream issue tracking this by any chance?

**Comment by Tyrrrz** [comment]
@DaRosenberg no, not for this case specifically.
The only relevant issue I found was this: https://github.com/dotnet/runtime/issues/24093

**Comment by DaRosenberg** [comment]
@Tyrrrz I'd like to wake this one back to life. We've been using the fix we implemented in our fork for more than 4 years now, and it's been 100% reliable across Windows, macOS and Linux.

Have you by any chance already implemented a fix for this in the main repo? If not, would you consider taking our fix as a PR at this point? It introduces `ParentProcessPipeSource` and `ParentProcessPipeTarget` implementations to deal with this issue.

The main commit with our fix is here:
https://github.com/Tyrrrz/CliWrap/commit/c6e25c396da192826ab9f25ed95a7c42bcc0011a

I ask because ideally we would like to get rid of our fork and move back onto the published package. But we can't do it without this fix, because interactively shelling out to external processes is a core scenario of our app.

**Comment by Tyrrrz** [comment]
Hi @DaRosenberg.

I haven't implemented a fix, and unfortunately I still don't think the suggested approach is a good general-purpose solution due to the problems I've outlined in the linked PR (breaking encapsulation, breaking `PipeTarget.Merge(...)`/high-level execution models, and relying upon undocumented interactions). I still think the proper solution is to introduce a cancellation token to the underlying stdin stream class in .NET.

**Comment by DaRosenberg** [comment]
@Tyrrrz I expected so, and I still find your reasoning sound.

Pending a fix in .NET (which may or may not come) I have an idea for how we could get rid of our fork.

1. The `ParentProcessPipeSource` and `ParentProcessPipeTarget` classes we can keep in our application.
2. The changes to the `Command.HandleStd*Async()` methods we can replace by having the `CopyFromAsync()` method in the above implementations simply do nothing except await their cancellation token (rather than throw `InvalidOperationException` as they currently do in our fork).
3. For the changes to `Command` it looks like we would be able to subclass it and add our customizations in a derived class instead if we can just change the `GetStartInfo()` and `ExecuteAsync()` methods from `private` to `protected`.
4. The change in `ProcessEx` is generic and should stay IMO. It simply ensures that `_nativeProcess.*.BaseStream` is used only if the `ProcessStartInfo` is configured to redirect the stream, which is no longer necessarily the case if a derived `Command.GetStartInfo()` method has configured the `ProcessStartInfo` differently.

So to change the premise a bit - would you instead take a PR that contains *only* these two changes?

- Allow `Command` to be subclassed by changing two members from `private` to `protected`
- [This change](https://github.com/Tyrrrz/CliWrap/commit/c6e25c396da192826ab9f25ed95a7c42bcc0011a#diff-b2b464760ca0b68dda1339b3bddbc73cd31dead9595b57a1650cbc3b090e8f62) to `ProcessEx`

**Comment by Tyrrrz** [comment]
@DaRosenberg yes, that sounds a lot more agreeable.

> * Allow `Command` to be subclassed by changing two members from `private` to `protected`

Wouldn't you only need to override `GetStartInfo()`? If `ParentProcessPipeTarget`, etc. don't throw but simply no-op, then you wouldn't need that custom conditional handling in `HandleXyzAsync()` methods (like you said), and thus `ExecuteAsync()` can remain the same?

**Comment by DaRosenberg** [comment]
(Or rather `CreateStartInfo()` as the method now seems to be named in the latest version of the code.)

**Comment by DaRosenberg** [comment]
PR open. Ultimately I decided to only change the `CreateStartInfo()` method after all.

**Comment by DaRosenberg** [comment]
@Tyrrrz I've realized a bit of a snag with this approach due to the way the fluent configuration API is implemented (every `WithXyz()` method creates a new instance of `Command`, so our derived class will be dropped as soon as we call one of these methods on it).

At first I assumed the immutability is to remove the risk of changing the configuration of a command that's already executing, but the `ExecuteAsync()` method doesn't actually touch any of the configuration properties - they are all "snapshotted" into `ProcessEx` when calling `CreateStartInfo()`, and after that point the configuration is no longer read (aside from some resource policy configuration also done up-front).

So I think we can safely "shift" the immutability from `Command` itself into an immutable configuration struct instead, which can be read atomically by `CreateStartInfo()` at the start of execution. Incidentally, I noticed there's also the `ICommandConfiguration` interface, but it seems to not really be used except in `CommandExecutionException`. The new immutable configuration struct can implement this interface.

This would be a completely non-breaking change.

I will close the PR and create a new one with the above.

**Comment by DaRosenberg** [comment]
OK, new PR is open. I decided to go with the 100% non-breaking approach.

**Comment by Tyrrrz** [comment]
> At first I assumed the immutability is to remove the risk of changing the configuration of a command that's already executing, but the `ExecuteAsync()` method doesn't actually touch any of the configuration properties - they are all "snapshotted" into `ProcessEx` when calling `CreateStartInfo()`, and after that point the configuration is no longer read (aside from some resource policy configuration also done up-front).

The immutability was not part of the design for the purpose of thread-safety, but for the purpose of maintaining the conceptual parallels with the idea of a "terminal command". Specifically, it matters the most in situations like these:

```csharp
var cmdA = Cli.Wrap(...).WithArguments(...);
var cmdB = cmdA | CliWrap(...).WithArguments(...);
```

Here, `cmdA` is combined with another command through piping to create `cmdB`. Internally, what `cmdA | ...` does is reconfigure the stdout pipe of `cmdA` to direct the data into the stdin of the command on the right.

Note the lines 143-144 below:

https://github.com/Tyrrrz/CliWrap/blob/95214f1881d9b9de11d538e1a2cad77d2ccbd404/CliWrap/PipeSource.cs#L135-L154

If the commands weren't immutable, the initialization of `cmdB` would have actually affected/mutated `cmdA`. This would have, of course, been weird and confusing, as we don't think of terminal commands being able to impact one-another like that. In the current design, because each change to the configuration creates a new command, the pipe operator simply results in a new copy of a command instead of modifying an existing instance.

So yeah, race conditions and thread-safety were never the primary reason for immutability, but mental models were. And I think it's a very important design aspect that we shouldn't break.

___

All that said, I also don't think the immutability is necessarily a blocker for you, depending on how exactly you're planning to use CliWrap.

For example, you could attach your custom command like this, with an execution model:

```csharp
public static async CommandTask<CommandResult> ExecuteWithoutRedirectionAsync(this Command cmd)
{
    // This is where you'd essentially substitute the `GetStartInfo()` method
    var cmdWrapped = new CustomCommand(cmd);

    return await cmdWrapped.ExecuteAsync();
}
```

This has some limitations of course, mainly the fact that you won't be able to execute your custom command with built-in execution models. But if your goal is to simply override how the Process is started, without necessarily getting involved in the whole of CliWrap's internal ecosystem, then it might be enough.

In fact, I'd actually probably be open to including a method like `ExecuteWithoutRedirectionAsync(this Command cmd)` in the library, seeing as implementing this functionality as part of an execution model is much less intrusive design-wise than implementing it as part of `Command` itself.

Let me know what you think.

**Comment by DaRosenberg** [comment]
@Tyrrrz For our purposes we don't need buffered, pull- or push-based execution (I assume these are what you are referring to as "built-in execution models", correct?) in this particular scenario, so I don't see any issue from that aspect.

However, I'm struggling to understand how a wrapping command would be able to override `CreateStartInfo()` of the wrapped command?

Here is what our specialized command subclass is doing now (assuming the changes in the PR):

```cs
class GitCommand(string targetFilePath, bool pipeStandardInputFromParent) : Command(targetFilePath)
{
    protected override ProcessStartInfo CreateStartInfo()
    {
        var startInfo = base.CreateStartInfo();

        if (pipeStandardInputFromParent)
        {
            startInfo.RedirectStandardInput = false;
        }

        return startInfo;
    }
}
```

And we have our no-op `PipeSource`:

```cs
class NoOpPipeSource : PipeSource
{
    public static NoOpPipeSource Instance { get; } = new NoOpPipeSource();

    public override Task CopyToAsync(Stream destination, CancellationToken cancellationToken = default)
    {
        return Task.Delay(Timeout.Infinite, cancellationToken);
    }
}
```

Then we configure and execute like this:

```cs
var isInteractive = true; // Command needs to interact with user?

var command =
    new GitCommand(mOptions.GitExecutablePath!, pipeStandardInputFromParent: isInteractive)
        .WithWorkingDirectory(workingDirectoryPath)
        .WithArguments(commandText)
        .WithStandardOutputPipe(PipeTarget.ToStream(outputStream))
        .WithStandardErrorPipe(PipeTarget.ToStream(errorStream))
        .WithValidation(CommandResultValidation.None);

if (isInteractive)
{
    // STDIN will be piped natively from parent process so use a PipeSource that does nothing:
    command = command.WithStandardInputPipe(NoOpPipeSource.Instance);
}

result = await cli.ExecuteAsync(cancellationToken);
```

I'm probably being daft, but it seems to me that inheriting is necessary. How else can we achieve setting `startInfo.RedirectStandardInput = false`?

**Comment by DaRosenberg** [comment]
But if you're willing to include the `ExecuteWithoutRedirectionAsync()` method on the `Command` class itself in `Command.Execution.cs`, where we have access to the construction of the `ProcessEx` instance, then it would be trivial to achieve this. Would just have to refactor slightly to avoid duplicating all the resource policy stuff.

**Comment by Tyrrrz** [comment]
> [@Tyrrrz](https://github.com/Tyrrrz) For our purposes we don't need buffered, pull- or push-based execution (I assume these are what you are referring to as "built-in execution models", correct?) in this particular scenario, so I don't see any issue from that aspect.

Yes, that's correct.

> However, I'm struggling to understand how a wrapping command would be able to override `CreateStartInfo()` of the wrapped command?

I guess "wrapping" is not an entirely accurate term to describe it. Essentially, you'd have your `CustomCommand` that defines the overriden `CreateStartInfo()` and then you copy all the configuration properties from a regular `Command`, which is passed to the constructor. So `CustomCommand`'s `ExecuteAsync()` will not actually call the other command's `ExecuteAsync()`.

`CustomCommand` could be defined like so:

```csharp
internal class CustomCommand(Command command)
    : Command(command.FilePath, command.Arguments, ...)
{
    protected override ProcessStartInfo CreateStartInfo()
    {
        var startInfo = base.CreateStartInfo();

        startInfo.RedirectStandardInput = false;
        startInfo.RedirectStandardOutput = false;
        startInfo.RedirectStandardError = false;

        return startInfo;
    }
}
```

> I'm probably being daft, but it seems to me that inheriting is necessary. How else can we achieve setting `startInfo.RedirectStandardInput = false`?

Inheriting is still necessary, but I'm saying that if you implement this custom behavior as an execution model (i.e. `ExecuteWithoutRedirectionAsync()`), instead of as part of command configuration or piping model, then you won't have an issue with the fact that the `WithXyz()` configuration methods return the base Command class (since you're attaching your behavior at the very end anyway).

**Comment by DaRosenberg** [comment]
@Tyrrrz Ah ok, I see what you mean now. Yes I think that would work.

We would need the version with a boolean for each stream, because in our scenario we do still have a need to redirect STDOUT and STDERR in some cases.

Also, if redirection is disabled for one or more of the streams, then `ProcessStartInfo.CreateNoWindow` must be set to `false` instead of `true´ for the native piping to/from the parent process to work on Windows (something I forgot to include in the code snippets I showed you above).

And of course we also still need the core change that fixes the `StandardInput`, `StandardOutput`, and `StandardError` properties on `ProcessEx` to return `Stream.Null` when not redirected.

If you can include those things 👆🏻 built-in, then I think we would be good.

But what should we do about the no-op pipe source/target? I believe it's necessary to use that for each stream that's **not** being redirected, lest the pipe source/target otherwise wait forever. Technically we could continue to provide and configure it from our application, and it would solve our problem, but it seems a bit brittle that you provide an `ExecuteWithoutRedirectionAsync()` in the library if it doesn't also ensure that a no-op pipe source/target is used for the non-directed streams.

**Comment by Tyrrrz** [comment]
> Also, if redirection is disabled for one or more of the streams, then `ProcessStartInfo.CreateNoWindow` must be set to `false` instead of `true` for the native piping to/from the parent process to work on Windows (something I forgot to include in the code snippets I showed you above).

Hmm, that means that it would also disable graceful cancellation support on Windows in that case.

> And of course we also still need the core change that fixes the `StandardInput`, `StandardOutput`, and `StandardError` properties on `ProcessEx` to return `Stream.Null` when not redirected.

That is not a problem 👍🏻 

> But what should we do about the no-op pipe source/target? I believe it's necessary to use that for each stream that's **not** being redirected, lest the pipe source/target otherwise wait forever.

By the way, does it need to be a special no-op pipe? Is it not enough to just use `PipeSource.Null`/`PipeTarget.Null`?

**Comment by DaRosenberg** [comment]
> By the way, does it need to be a special no-op pipe? Is it not enough to just use `PipeSource.Null`/`PipeTarget.Null`?

I'm struggling to remember the details now, it was so long ago...

The core `PipeSource`/`PipeTarget` classes have since changed a lot. It used to be that `PipeTarget.Null` created a target that actually performed a `CopyToAsync()` from the process stream into `Stream.Null`, and I think that caused issues when that stream was not being redirected. It would end up waiting forever, and because a stream read from STDOUT and STDERR is inherently not cancellable, the read operation would be abandoned and sit there and eat up whatever character came next, even long after the `PipeTarget` had been abandoned. Or something along those lines.

However, it looks like in 2025, `PipeTarget.Null` is now a different thing which just returns a completed task and never actually touches any stream at all. So it might actually work now without any specialized no-op source/target implementations, as you suggest.

I would propose that you implement the changes in a branch (overriding the command configuration with `PipeSource.Null`/`PipeTarget.Null` for any non-redirected streams) and release it in a preview package first. I can then make the corresponding changes in our application, and test the functionality across both macOS, Windows and Linux. If it works out like we think, you can integrate the changes and get it out into the next release. What do you think?

**Comment by Tyrrrz** [comment]
@DaRosenberg Because the new execution model would have to set `CreateNoWindow = false`, I've re-evaluated this approach again, as it would have wider implications than originally expected. Ultimately, it seems that whatever escape hatch I end up providing, it's going to provide a very powerful way to shoot yourself in the foot, so I just decided to offer a method overload that allows you to configure `ProcessStartInfo` directly.

See #290.

This is probably the simplest and least-of-all-evils option, but it obviously breaks CliWrap's abstraction model, so should be used at your own risk.

For your use case, you should be able to do the following:

```csharp
cmd.ExecuteAsync(
    startInfo =>
    {
        // The below would be conditional on your logic
        startInfo.RedirectStandardInput = false;
        startInfo.RedirectStandardOutput = false;
        startInfo.RedirectStandardError = false;
        startInfo.CreateNoWindow = false;
    },
    null
);
```

The delegate is executed after `CreateStartInfo()`, so you'll get the same behavior as with overriding.

As of a recent commit, the process streams now also default to `Stream.Null`:

https://github.com/Tyrrrz/CliWrap/commit/9b9384db16c2b759023e2ae2353c58e43fe74542

And, as discussed, you can probably get away with using `PipeSource.Null`/`PipeTarget.Null` instead of your own custom no-op implementation.

I've released a pre-release package version for you to try: https://www.nuget.org/packages/CliWrap/3.9-alpha.1

**Comment by DaRosenberg** [comment]
@Tyrrrz I tested this out against the alpha build, and I've managed to get it working - with some caveats.

`PipeSource.Null` instead of `NoOpPipeSource` works fine, as long as `ProcessStartInfo.RedirectStandardInput = false`.

However I think there's an issue with the way `PipeSource.Null` and `PipeTarget.Null` are implemented:

<img width="1285" alt="Image" src="https://github.com/user-attachments/assets/2f8ec223-e8e0-4ad7-b656-2677a5a30a8a" />

Whenever the child process (`git` in our case) tries to write to either STDOUT or STDERR (both of which I'm piping to `PipeTarget.Null` it receives a `SIGPIPE` and errors out with exit code 141 (pipe fail), presumably because the stream has been disposed.

Using `PipeTarget.FromStream(Stream.Null)` instead of `PipeTarget.Null` works around the issue, presumably because that does an actual `CopyToAsync()` which doesn't return until cancelled by the provided cancellation token, thereby deferring the disposal of the stream until after the child process has exited.

(Similarly, using our own `NoOpPipeTarget` also works around the issue, because it too doesn't return until cancelled.)

This is on macOS, and I'm not sure if the behavior is the same on Windows, but if I'm understanding this correctly, the way this is currently implemented I struggle to see how using `PipeTarget.Null` can possibly work in any scenario where the child process actually tries to write something to the redirected stream on Unix/Linux.

**Comment by Tyrrrz** [comment]
@DaRosenberg do I understand the situation correctly:

1. `WithStandardOutputPipe(PipeTarget.Null)`
2. With `RedirectOutputStream = false`

...results in `SIGPIPE`?

That doesn't make sense given that `process.StandardOutput` will be `Stream.Null` in that case:

https://github.com/Tyrrrz/CliWrap/blob/9b9384db16c2b759023e2ae2353c58e43fe74542/CliWrap/Utils/ProcessEx.cs#L29-L42

So it shouldn't be able to dispose the actual process's streams.

**Comment by DaRosenberg** [comment]
@Tyrrrz No I mean if you just do `WithStandardOutputPipe(PipeTarget.Null)` without modifying the `ProcessStartInfo`.

**Comment by Tyrrrz** [comment]
@DaRosenberg right, then that behaves as expected. That's covered in the readme, as well as the method documentation:

![Image](https://github.com/user-attachments/assets/b700f979-dbff-4ab0-a41a-ebea93de12a5)

Related issue: https://github.com/Tyrrrz/CliWrap/issues/145#issuecomment-1100680547

**Comment by DaRosenberg** [comment]
Ok, I see. 

So basically, invoking Git is one of those cases where piping to `Stream.Null` is needed, because apparently it actively checks the pipe?

I’ll do some more testing to ensure this works also on Windows and Linux, but barring any unforeseen issues, I think we are good. 👍🏻 

I’d like to take this opportunity to express our appreciation and thank you for all your work maintaining this library, and for engaging with us to help solve for our scenario. It’s something we don’t take for granted.

**Comment by DaRosenberg** [comment]
@Tyrrrz Out of curiosity, is there a reason to not simply defer the disposing of the base streams until after the process has exited by having `PipeTarget.Null` stick around a bit longer like our `NoOpPipeTarget` did?

```cs
public static PipeTarget Null { get; } =
    Create(
        (_, cancellationToken) => Task.Delay(Timeout.Infinite, cancellationToken)
    );
```

Could you not then get rid of the warning in the readme and consider `PipeTarget.Null` safe for all scenarios?

**Comment by Tyrrrz** [comment]
It might, but there are a couple of issues I see with it.

First, the cancellation. Currently, CliWrap only cancels stdout/stderr pipes if the whole process is canceled. Otherwise, if the pipes are open for whatever reason, it assumes that there's still data left to handle, even if the process itself has exited (which is a common scenario if you run a lot of short-lasting but output-heavy processes in quick succession).

https://github.com/Tyrrrz/CliWrap/blob/9b9384db16c2b759023e2ae2353c58e43fe74542/CliWrap/Command.Execution.cs#L230-L251

So that `Task.Delay(Timeout.Infinite, cancellationToken)`'s `cancellationToken` will never trigger in most situations.

Second, if the stdout/stderr stream is open, the data has to be read. Otherwise, there's a risk, if the process writes enough (a lot) of data to either stream, it will hit the buffer limit, and the next `Console.WriteLine` (or whatever equivalent) will lock until that buffer is exhausted (or the pipe is closed).

`PipeTarget.Null` works by immediately closing the pipe, preventing any deadlocks from occurring.

`PipeTarget.ToStream(Stream.Null)` keeps the pipes open, but still reads all the data and simply discards it.

Your `PipeTarget.NoOp` will never finish executing in the current implementation, due to relying on a cancellation signal that may never trigger -- but also risks creating deadlock scenarios by keeping the stdout/stderr pipes open without reading them.

**Comment by Tyrrrz** [comment]
Generally, the existing test suite should already cover the aforementioned deadlock scenarios, so if the tests pass with your implementation, then it's fine.
